-- 코드를 입력하세요
SELECT FOOD_PRODUCT.PRODUCT_ID, PRODUCT_NAME,SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT
LEFT JOIN FOOD_ORDER ON FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
WHERE MONTH(PRODUCE_DATE) = 5
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC,PRODUCT_ID