-- 코드를 입력하세요
SELECT product_code, sum(sales_amount) * price AS "SALES"
FROM PRODUCT
LEFT JOIN OFFLINE_SALE ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, product_code