-- 코드를 입력하세요
SELECT USER_ID,NICKNAME,SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD as A
JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = "Done"
GROUP BY A.WRITER_ID
HAVING SUM(A.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC
